# This is a basic workflow to help you get started with Actions

name: TestApiCalculadora

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a command to install Flask
      - name: Install flask
        run: pip3 install flask

      # Runs a set of commands using the runners shell
      - name: Execute the app
        run: python3 api_calculadora.py &
        
      # Run tests with curl command and redirect with grep
      - name: Test suma function
        run: curl http://127.0.0.1:5000/suma/1/5 | grep '{"resultat":6}'
      - name: Test resta function
        run: curl http://127.0.0.1:5000/resta/9/3 | grep '{"resultat":6}'
      - name: Test multiplica function
        run: curl http://127.0.0.1:5000/multiplica/3/2 | grep '{"resultat":6}'
      - name: Test divideix function
        run: curl http://127.0.0.1:5000/divideix/12/2 | grep '{"resultat":6.0}'
